### ISSUE TITLE
Failure on running sync-p-hikey960.sh

### ISSUE THREAD

**Issue by guojuntang** [linaro-swg/optee_android_manifest#58]
Hello.
I am trying to fetch the source code by running sync-p-hikey960.sh,but it fail!
Here is error log:
```
Fetching project platform/prebuilts/gdb/darwin-x86
Skipped fetching project platform/prebuilts/gdb/darwin-x86 (already have persistent ref)
Fetching project platform/frameworks/opt/inputconnectioncommon
Fetching fatal: unable to access 'https://android.googlesource.com/platform/system/netd/': Operation timed out after 300047 milliseconds with 0 out of 0 bytes received
error: unable to read sha1 file of gradle-2.14.1-bin.zip (f04eb92f3f022583e9b788086d20a16ebb04dff9)
error: unable to read sha1 file of gradle-2.4-all.zip (81710873a6413e6f31c72d16078c9910301f63ac)
error: unable to read sha1 file of gradle-3.2-bin.zip (0ffb0cb09c2921602f1a8f15969e2c2bc4f6ff94)
error: unable to read sha1 file of gradle-3.3-bin.zip (5c8aa568d559da964aa652537b29d604d0aeb61a)
error: unable to read sha1 file of gradle-3.4.1-bin.zip (a5d650ddf21149c5d2ca3b114887722a58d00ef3)
error: unable to read sha1 file of gradle-4.0-bin.zip (efaad69ebf8961a43097649b5b1540285d03450f)
error: unable to read sha1 file of gradle-4.1-bin.zip (a46c12157010d729ff2b1975f3f134e4849f79b8)
error: unable to read sha1 file of gradle-4.3-bin.zip (d8422a9099f576ee1e53931980c582be550bfc6b)
error: unable to read sha1 file of gradle-4.4-bin.zip (48b03d0ab1bc41bcd48911ff20632eeb0cf0f0db)
error: unable to read sha1 file of gradle-api-2.14.1.jar (a365aa49fc9006ef299d2e2cb3d357771a5e0123)
error: unable to read sha1 file of gradle-api-3.4.1.jar (a14c13e5222087218882bed3244a104d1b5a48bb)
error: unable to read sha1 file of gradle-api-3.5-20170307000048+0000.jar (147791798b5085bb1cd7ba02815fd516e00921df)
project platform/external/ncurses
Fetching project platform/platform_testing
Fetching project platform/external/python/google-api-python-client
Fetching project device/generic/mini-emulator-armv7-a-neon
Fetching project platform/external/bart
Fetching project platform/external/googletest
Fetching project device/generic/armv7-a-neon
Fetching project platform/packages/providers/UserDictionaryProvider
Fetching project platform/packages/apps/StorageManager
Fetching project platform/external/libmicrohttpd
Fetching project platform/developers/demos
Traceback (most recent call last):
  File "/home/scnu602/optee-aosp/optee_android_manifest/.repo/repo/main.py", line 547, in <module>
    _Main(sys.argv[1:])
  File "/home/scnu602/optee-aosp/optee_android_manifest/.repo/repo/main.py", line 522, in _Main
    result = repo._Run(argv) or 0
  File "/home/scnu602/optee-aosp/optee_android_manifest/.repo/repo/main.py", line 184, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/scnu602/optee-aosp/optee_android_manifest/.repo/repo/subcmds/sync.py", line 840, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/home/scnu602/optee-aosp/optee_android_manifest/.repo/repo/project.py", line 1379, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync, submodules=submodules)
  File "/home/scnu602/optee-aosp/optee_android_manifest/.repo/repo/project.py", line 2587, in _InitWorkTree
    raise GitError("cannot initialize work tree")
error.GitError: cannot initialize work tree
```

**Comment by vchong** [comment]
Is this a new or existing source tree? Which branch are you using? Have you modified anything? This is usually due to corrupted repos. Try deleting the files below and sync again.

```
system/netd
.repo/projects/system/netd.git
.repo/project-objects/platform/system/netd.git
tools/external/gradle
.repo/projects/tools/external/gradle.git
.repo/project-objects/platform/tools/external/gradle.git
```

**Comment by guojuntang** [comment]
It seems work.
Thanks!

**Comment by vchong** [comment]
Great. You're welcome! Please note though that the hikey960 build currently doesn't work very well, and not easy to work with due to adb issues.
